name: FunctionalServerControl
version: '${project.version}'
main: by.alis.functionalservercontrol.spigot.FunctionalServerControlSpigot
api-version: 1.13
authors: [ ALis ]
description: Система блокировок аккаунтов
website: https://vk.com/alphatwo
softdepend: [Vault, LuckPerms, ProtocolLib]
commands:
  kick:
  functionalservercontrol:
    aliases: [fsc, fscontrol]
  ban:
  tempban:
    aliases: [temporaryban]
  kickall:
  unban:
  unbanall:
  crazykick:
    aliases: [ckick]
  dupeip:
  cheatcheck:
    aliases: [ccheck]
  tempbanip:
    aliases: [temporarybanip]
  banip:
  mute:
  tempmute:
    aliases: [temporarymute]
  unmute:
  muteip:
  tempmuteip:
  unmuteall:
