name: FunctionalBans
version: '${project.version}'
main: by.alis.functionalbans.spigot.FunctionalBansSpigot
api-version: 1.13
authors: [ ALis ]
description: Система блокировок аккаунтов
website: https://vk.com/alphatwo
softdepend: [Vault, LuckPerms, ProtocolLib]
commands:
  kick:
    description: The main command for kicking the specified players
  functionalbans:
    aliases: [fb, fbans, funcbans]
    description: The main command of the plugin
  ban:
    aliases: [permanentban]
    description: The main command for blocking the specified players
  tempban:
    aliases: [temporaryban]
    description: Basic command for temporarily blocking accounts
  kickall:
    description: Kicks all players from the server
  unban:
    description: Command to unban an account
  unbanall:
    description: Unbans all banned accounts
  crazykick:
    description: Throws a player with hieroglyphs to full screen
    aliases: [ckick]
  dupeip:
    description: dupeip
  test:
    description: test
